### ISSUE TITLE
How to change the boot partition size?

### ISSUE THREAD

**Issue by yoshito-okada** [jubilinux/jubilinux#7]
I am playing with custom kernels and want to put multiple kernel images on the boot partition but could not because of the limited size of the partition.
I guess the partition size is determined by the size of edison-image-edison.hddimg in a jubilinux archive, but am not sure how to modify this file.
Could you give me an instruction?

**Comment by esialb** [comment]
The edison's U-Boot seems to be fine with repartitioning during boot, but won't allow the Edison to be reflashed until the original partitioning table is restored.  I suggest deleting the /boot partition from gdisk then recreating a new one with the same partition number, but larger.  That will probably work, but I haven't tried it.  A similar technique is used to expand the root filesystem.

**Comment by yoshito-okada** [comment]
Thank you for the instruction.  I will try!   I will close the issue for now and re-open if something unexpected happens.
